name: Trigger GitHub Pages Site Rebuild on Push

on:
  push:
    branches: [main]

jobs:
  trigger:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Trigger Repository Dispatch in BASE
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await octokit.rest.repos.createDispatchEvent({
              owner: 'Tristie',
              repo: 'thetestmainfolderpagessubmodule',
              event_type: 'subpage-updated',
            });
