name: Trigger GitHub Pages Site Rebuild on Push

on:
  push:
    branches: [main]

jobs:
  trigger:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Trigger Repository Dispatch on pages repo
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: '${{ github.event.repository.owner.login }}',
              repo: 'thetestmainfolderpagessubmodule',
              event_type: 'subpage-updated',
            });
